@extends('portal.layout', ['title' => 'Receipt '.$payment->reference])

@section('portal')
    <p class="text-sm text-body/80" data-no-print><a class="text-brand hover:underline" href="{{ route('portal.invoices') }}">← Invoices</a>
        · <button type="button" class="text-brand hover:underline" data-print>Print or save as PDF</button></p>

    <article class="mt-6 max-w-[720px] space-y-6" data-printable>
        <div class="flex flex-wrap justify-between gap-6">
            @include('portal.partials.firm-letterhead')
            <div class="text-sm">
                <p class="text-lg font-semibold text-ink">Payment receipt</p>
                <p>{{ $payment->reference }}</p>
            </div>
        </div>

        <dl class="grid gap-x-6 gap-y-2 text-sm sm:grid-cols-[max-content_1fr]">
            <dt class="font-semibold">Received from</dt><dd>{{ $payment->client->display_name }} ({{ $payment->client->reference }})</dd>
            <dt class="font-semibold">Amount received</dt><dd class="font-semibold text-ink">{{ $money((int) $payment->received_minor) }}</dd>
            <dt class="font-semibold">Date</dt><dd>{{ ($payment->paid_at ?? $payment->received_on ?? $payment->verified_at)?->timezone(\App\Domain\Operations\Settings::get('firm.timezone'))->format('j M Y') }}</dd>
            <dt class="font-semibold">Method</dt><dd>{{ $payment->methodLabel() }}@if ($payment->channel) ({{ $payment->channel }})@endif</dd>
            @if ($payment->invoice)<dt class="font-semibold">For invoice</dt><dd><a class="text-brand hover:underline" href="{{ route('portal.invoices.show', $payment->invoice) }}">{{ $payment->invoice->reference }}</a> – {{ $payment->invoice->title }}</dd>@endif
            @if ($payment->unapplied_minor > 0)<dt class="font-semibold">Held as credit</dt><dd>{{ $money($payment->unapplied_minor) }} (more than the invoice balance; we will contact you about it)</dd>@endif
            @if ($payment->refunded_minor > 0)<dt class="font-semibold">Refunded</dt><dd>{{ $money($payment->refunded_minor) }}</dd>@endif
        </dl>
        <p class="text-sm text-body/80">This receipt confirms money received by {{ \App\Domain\Operations\Settings::get('site.title') }}. It was generated by our client portal.</p>
    </article>
@endsection
